# Site settings
title: 新闻动态
email: business@suicloud.com
description: Indoorwise, 室内通专注室内导航和室内定位的行业解决方案
keywords: 室内导航，室内定位，iBeacon，室内地图，近场感应
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.indoorwise.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
#timezone: Asia/Shanghai

#paginate settings
paginate: 10
paginate_path: "page:num"

# Build settings
markdown: kramdown
